"""esquema inicial

Revision ID: 333e9f6ceac0
Revises: 
Create Date: 2026-09-29 02:58:38.477215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333e9f6ceac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('contador',
    sa.Column('prefijo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefijo')
    )
    op.create_table('setting',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('validez_dias', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('flete', sa.Integer(), nullable=False),
    sa.Column('iva_pct', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=80), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=False),
    sa.Column('tarifa_dia', sa.Integer(), nullable=False),
    sa.Column('tarifa_semana', sa.Integer(), nullable=True),
    sa.Column('tarifa_mes', sa.Integer(), nullable=True),
    sa.Column('garantia', sa.Integer(), nullable=False),
    sa.Column('valor_reposicion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('arriendo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('lugar_uso', sa.String(length=250), nullable=True),
    sa.Column('flete', sa.Integer(), nullable=False),
    sa.Column('recargo', sa.Integer(), nullable=False),
    sa.Column('iva_pct', sa.Integer(), nullable=False),
    sa.Column('garantia_monto', sa.Integer(), nullable=False),
    sa.Column('garantia_devuelta', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cotizacion_id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('cotizacion_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('descuento_pct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arriendo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arriendo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Integer(), nullable=False),
    sa.Column('notas_devolucion', sa.String(length=250), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('descuento_pct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arriendo_id'], ['arriendo.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arriendo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arriendo_id'], ['arriendo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('arriendo_item')
    op.drop_table('movimiento_inventario')
    op.drop_table('mantencion')
    op.drop_table('cotizacion_item')
    op.drop_table('arriendo')
    op.drop_table('equipo')
    op.drop_table('cotizacion')
    op.drop_table('usuario')
    op.drop_table('setting')
    op.drop_table('contador')
    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
